num_worker: 2
work_dir: ./work_dir/ntu_small/joint_CoM_1

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: ./data/ntu_small/NTU_SMALL.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 30
  normalization: False
  random_rot: False
  p_interval: [1.0]
  bone: False

test_feeder_args:
  data_path: ./data/ntu_small/NTU_SMALL.npz
  split: test
  window_size: 30
  p_interval: [1.0]
  bone: False
  debug: False

# model
model: model.HDGCN.Model
model_args:
  num_class: 5
  num_point: 25
  num_person: 1
  graph: graph.ntu_rgb_d_hierarchy.Graph
  graph_args:
    labeling_mode: spatial
    CoM: 1

# optim (NTU-style)
weight_decay: 0.0004
base_lr: 0.01
warm_up_epoch: 1

# training
device: []
batch_size: 8
test_batch_size: 8
num_epoch: 10
nesterov: True
